### PR TITLE
Remove did.globals

### PR DESCRIPTION
**Pull request by ehennestad**
### Summary
This PR removes the `did.globals` and the reliance on `did.globals` to set global variables.

The did.globals is replaced by the following:

- `did.common.PathConstants`: A class with constant properties representing the path constants that were part of the did_global structure
- `did.common.getCache`: A function with a persistent variable keeping the cache in memory so that it is not reinitialised every time it is requested.

Instead of running `did.globals`, the above class/function is referred to when needed in the +did namespace.

### Notes:
- The `did_globals.path.definition_names` and `did_globals.path.definition_locations` were replaced by `did.common.PathConstants.definitions` which is a `containers.Map` object where the names are the keys and the locations are the values.

- I also added the function +did/+common/+utility/replace_didpath.m as it was present in two locations before

Adding a containers.Map object to a constant property allows updating the keys and values at later times, which is needed when using DID from NDI, where the definition map is updated with names and locations from NDI

### Discussion/Questions
- Will a definition name ever have the placeholder/name (i.e `$DIDDOCUMENT_EX1`) always be present as the first part of a path?
- Does the `did.common` namespace sound good for these global replacements?

### CODE REVIEW

**Comment by stevevanhooser** [comment]
Let's think about `common` because it is something we could use many times.

I had used the directory `ndi_common` to refer to definition files that did not depend on any specific implementation (could be used for Matlab, python, etc). Here, the `did.common` refers to tools that are used to access the common directory. I think that tracks well.



I had intended that placeholders (for example, `$DIDDOCUMENT_EX1`) could be substituted anywhere via a regular expression. So they might not appear at all, might appear in the middle, etc. Right now they only appear at the beginning.

**Comment by stevevanhooser** [comment]
This update is not yet compatible with `ndi_Init.m` because that function calls `did.globals`. Is the idea that we will not need to call `ndi_Init.m` anymore and we can remove it?

**Comment by ehennestad** [comment]
> This update is not yet compatible with `ndi_Init.m` because that function calls `did.globals`. Is the idea that we will not need to call `ndi_Init.m` anymore and we can remove it?

Yes, I have done a similar change for NDI, will make that into a PR as well

**Comment by stevevanhooser** [comment]
I moved these pull requests to target a copy of `main` called `main_v080_refactor` so we can work through the requests without touching `main`.

**Comment by stevevanhooser** [comment]
(I made the new branch because we have to flip NDI and DID at the same time overall)

**Pull request merged**
