### PR TITLE
Add argument blocks to functions that relied on vlt.data.assign

### PR DESCRIPTION
**Pull request by ehennestad**
## Summary

Added argument blocks to all functions where a combination of `varargin` and `vlt.data.assign` function was used.

This should make the code clearer and provide better input argument validation.

## Note:
Had to change the order of arguments in the following function: `did.file.dumbjsondb/search`. Does any other function (external or internal) rely on this one? 

Also, I could not understand it the current arguments are in line with the superclass definition.

### CODE REVIEW

**Comment by stevevanhooser** [comment]
Thanks!

Is this PR superseded by PR#71? PR#71 seems to have all of these changes, right?

**Comment by stevevanhooser** [comment]
Re: `did.file.dumbjsondb/search` 

Our old file system database system used these. That is, the class `./+did/+implementations/matlabdumbjsondb.m`.  We probably use this in some tests to compare output of the sql with the slower but really well tested dumbjsondb.

**Comment by ehennestad** [comment]
> Thanks!
> 
> Is this PR superseded by PR#71? PR#71 seems to have all of these changes, right?

Yes

**Comment by ehennestad** [comment]
> Thanks!
> 
> Is this PR superseded by PR#71? PR#71 seems to have all of these changes, right?

Yes, exactly

**Pull request merged**
